# Site settings
title: Lorem Ipsum - Web Developer
description: "A blog about lorem ipsum ..."
baseurl: ""
url: "http://victorvoid.github.io/space-jekyll-template/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Cronak
user_title: Cronak
email: cronak2355@gmail.com
twitter_username: cronak2355
github_username: cronak2355
discord_invite: X
linkedin_public_url: taewon-kim-a08588386/ # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: X
profile_picture: /assets/img/Profile/Profile-Picture-1.jpg

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/cronak2355
      new_tab: true
      key_trigger: g
    - title: X
      url: https://x.com/cronak2355
      key_trigger: x
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name:
    url:
  - name:
    url:
  - name:
    url: 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
